### ISSUE TITLE
Task 3: In the people section, images become black  squares

### ISSUE THREAD

**Issue by patrick-mzaaber** [oibeirut/oib_website#8]
(https://www.orient-institut.org/people/fellows/), Upon hovering above images on the same page, they become over-saturated. (This matter is occurring as well with the events section – poster shown on the original page before being maximized; “The “News and Publications” on our main page is facing the same troubles as well – Publications logos are pixelated/not  clear).

**Comment by tillgrallert** [comment]
I would say this is a duplicate of #7
